/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness check
     * @description Check if the service and all dependencies are ready
     */
    get: operations['checkReadiness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness check
     * @description Check if the service is alive
     */
    get: operations['checkLiveness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness check (alias)
     * @description Alias for /health endpoint
     */
    get: operations['checkReady'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Prometheus metrics
     * @description Expose Prometheus metrics for monitoring
     */
    get: operations['getMetrics'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a new user
     * @description Create a new user account with the default role assigned
     */
    post: operations['register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate user
     * @description Authenticate with email and password, returns access and refresh tokens
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh access token
     * @description Exchange a valid refresh token for new access and refresh tokens
     */
    post: operations['refreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout current session
     * @description Revoke the current refresh token
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout all sessions
     * @description Revoke all refresh tokens for the current user
     */
    post: operations['logoutAll'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/forgot-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request password reset
     * @description Request a password reset email. Always returns success to prevent email enumeration.
     */
    post: operations['forgotPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset password
     * @description Reset password using a valid reset token
     */
    post: operations['resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user
     * @description Get the authenticated user's profile with roles and permissions
     */
    get: operations['getCurrentUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List active sessions
     * @description Get all active sessions for the current user
     */
    get: operations['getSessions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sessions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke session
     * @description Revoke a specific session by ID
     */
    delete: operations['revokeSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List users
     * @description Get paginated list of users
     */
    get: operations['listUsers'];
    put?: never;
    /**
     * Create user
     * @description Create a new user (admin only)
     */
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user
     * @description Get user by ID
     */
    get: operations['getUser'];
    /**
     * Update user
     * @description Update user details
     */
    put: operations['updateUser'];
    post?: never;
    /**
     * Delete user
     * @description Soft delete a user
     */
    delete: operations['deleteUser'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change password
     * @description Change user password (owner only or admin)
     */
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/activate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Activate user
     * @description Activate a pending or inactive user
     */
    post: operations['activateUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/deactivate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Deactivate user
     * @description Deactivate an active user
     */
    post: operations['deactivateUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/ban': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ban user
     * @description Ban a user with reason
     */
    post: operations['banUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user roles
     * @description Get roles assigned to a user
     */
    get: operations['getUserRoles'];
    /**
     * Set user roles
     * @description Replace all roles for a user
     */
    put: operations['setUserRoles'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/roles/{roleId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Assign role to user
     * @description Assign a specific role to a user
     */
    post: operations['assignRole'];
    /**
     * Revoke role from user
     * @description Remove a specific role from a user
     */
    delete: operations['revokeRole'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/permissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user permissions
     * @description Get effective permissions for a user (aggregated from all roles)
     */
    get: operations['getUserPermissions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List roles
     * @description Get all roles
     */
    get: operations['listRoles'];
    put?: never;
    /**
     * Create role
     * @description Create a new role
     */
    post: operations['createRole'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/roles/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get role
     * @description Get role with permissions
     */
    get: operations['getRole'];
    /**
     * Update role
     * @description Update role details
     */
    put: operations['updateRole'];
    post?: never;
    /**
     * Delete role
     * @description Delete a role (system roles cannot be deleted)
     */
    delete: operations['deleteRole'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/roles/{id}/permissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Set role permissions
     * @description Replace all permissions for a role
     */
    put: operations['setRolePermissions'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/roles/{id}/permissions/{permissionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add permission to role */
    post: operations['addPermissionToRole'];
    /** Remove permission from role */
    delete: operations['removePermissionFromRole'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/roles/{id}/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get users with role
     * @description Get all users assigned to a specific role
     */
    get: operations['getUsersWithRole'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/permissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List permissions
     * @description Get all permissions, optionally filtered by resource
     */
    get: operations['listPermissions'];
    put?: never;
    /**
     * Create permission
     * @description Create a custom permission
     */
    post: operations['createPermission'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/permissions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get permission */
    get: operations['getPermission'];
    /**
     * Update permission
     * @description Update permission description
     */
    put: operations['updatePermission'];
    post?: never;
    /**
     * Delete permission
     * @description Delete a custom permission (system permissions cannot be deleted)
     */
    delete: operations['deletePermission'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * Format: password
       * @description Must contain uppercase, lowercase, number, and special character
       * @example SecurePass123!
       */
      password: string;
      /** @example John Doe */
      full_name: string;
    };
    LoginRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * Format: password
       * @example SecurePass123!
       */
      password: string;
    };
    RefreshTokenRequest: {
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      refresh_token: string;
    };
    ForgotPasswordRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
    };
    ResetPasswordRequest: {
      reset_token: string;
      /** Format: password */
      new_password: string;
    };
    AuthResponse: {
      user?: components['schemas']['UserResponse'];
      access_token?: string;
      refresh_token?: string;
      /** Format: date-time */
      expires_at?: string;
    };
    AuthUserResponse: {
      /** Format: uuid */
      id?: string;
      /** Format: email */
      email?: string;
      full_name?: string;
      /** @enum {string} */
      status?: 'active' | 'inactive' | 'banned';
      roles?: string[];
      permissions?: string[];
    };
    SessionResponse: {
      /** Format: uuid */
      id?: string;
      device_info?: components['schemas']['DeviceResponse'];
      ip_address?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      last_used_at?: string | null;
      is_current?: boolean;
    };
    DeviceResponse: {
      user_agent?: string;
      platform?: string;
      browser?: string;
    };
    ForgotPasswordResponse: {
      /** @example If an account exists with this email, a password reset link has been sent. */
      message?: string;
      /** Format: date-time */
      expires_at?: string;
    };
    MessageResponse: {
      message?: string;
    };
    UserResponse: {
      /** Format: uuid */
      id?: string;
      /** Format: email */
      email?: string;
      full_name?: string;
      avatar?: string | null;
      /** @enum {string} */
      status?: 'pending' | 'active' | 'inactive' | 'banned';
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    UserListResponse: {
      items?: components['schemas']['UserResponse'][];
      /** Format: int64 */
      total?: number;
      page?: number;
      limit?: number;
      total_pages?: number;
      has_next?: boolean;
      has_prev?: boolean;
    };
    CreateUserRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
      full_name: string;
      role_ids?: string[];
    };
    UpdateUserRequest: {
      full_name?: string;
      avatar?: string;
    };
    SetRolesRequest: {
      role_ids: string[];
    };
    RoleResponse: {
      /** Format: uuid */
      id?: string;
      name?: string;
      display_name?: string;
      description?: string;
      is_system?: boolean;
      is_default?: boolean;
      priority?: number;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    RoleWithPermissionsResponse: components['schemas']['RoleResponse'] & {
      /** @description Permission codes (e.g., ["users:read", "users:create"]) */
      permissions?: string[];
    };
    CreateRoleRequest: {
      /** @example content_editor */
      name: string;
      /** @example Content Editor */
      display_name: string;
      description?: string;
      permission_ids?: string[];
    };
    UpdateRoleRequest: {
      display_name?: string;
      description?: string;
    };
    SetPermissionsRequest: {
      permission_ids: string[];
    };
    PermissionResponse: {
      /** Format: uuid */
      id?: string;
      /** @example users */
      resource?: string;
      /** @example read */
      action?: string;
      /** @example users:read */
      code?: string;
      description?: string;
      is_system?: boolean;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    CreatePermissionRequest: {
      /** @example articles */
      resource: string;
      /** @example publish */
      action: string;
      /** @example Publish articles */
      description?: string;
    };
    UpdatePermissionRequest: {
      description?: string;
    };
    ChangePasswordRequest: {
      /** Format: password */
      current_password: string;
      /**
       * Format: password
       * @description Must contain uppercase, lowercase, number, and special character
       */
      new_password: string;
      /**
       * Format: password
       * @description Must match new_password
       */
      confirm_password: string;
    };
    BanUserRequest: {
      /** @example Violation of terms of service */
      reason: string;
    };
    HealthResponse: {
      /** @enum {string} */
      status?: 'healthy' | 'unhealthy';
      /**
       * @example {
       *       "database": {
       *         "status": "healthy"
       *       },
       *       "redis": {
       *         "status": "healthy"
       *       }
       *     }
       */
      checks?: {
        [key: string]: {
          /** @enum {string} */
          status?: 'healthy' | 'unhealthy';
          message?: string;
        };
      };
    };
    LivenessResponse: {
      /**
       * @example ok
       * @enum {string}
       */
      status?: 'ok';
    };
    ErrorResponse: {
      error?: {
        /** @example VALIDATION_ERROR */
        code?: string;
        /** @example Invalid input */
        message?: string;
        details?: {
          field?: string;
          message?: string;
        }[];
      };
      /** @description Request trace ID for debugging */
      trace_id?: string;
    };
  };
  responses: never;
  parameters: {
    /** @description User ID */
    UserId: string;
    /** @description Role ID */
    RoleId: string;
    /** @description Role ID */
    RoleIdPath: string;
    /** @description Permission ID */
    PermissionId: string;
    /** @description Permission ID */
    PermissionIdPath: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  checkReadiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
      /** @description Service is not ready */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  checkLiveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LivenessResponse'];
        };
      };
    };
  };
  checkReady: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  getMetrics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Prometheus metrics in text format */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description User registered successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Email already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          /** @description Seconds to wait before retrying */
          'Retry-After'?: number;
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Account locked or inactive */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          'Retry-After'?: number;
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenRequest'];
      };
    };
    responses: {
      /** @description Tokens refreshed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Invalid or expired refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logoutAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All sessions logged out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordRequest'];
      };
    };
    responses: {
      /** @description Password reset requested (always returns success) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForgotPasswordResponse'];
        };
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest'];
      };
    };
    responses: {
      /** @description Password reset successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Invalid or expired token, or weak password */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthUserResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of active sessions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionResponse'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  revokeSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listUsers: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        status?: 'pending' | 'active' | 'inactive' | 'banned';
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserListResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires users:list permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserRequest'];
      };
    };
    responses: {
      /** @description User created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires users:create permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Email already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires users:read permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest'];
      };
    };
    responses: {
      /** @description User updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires users:update permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires users:delete permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description Password changed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Invalid current password or weak new password */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - can only change own password */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  activateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User activated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires users:manage permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid status transition */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deactivateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User deactivated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires users:manage permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid status transition */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  banUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BanUserRequest'];
      };
    };
    responses: {
      /** @description User banned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires users:manage permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid status transition */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getUserRoles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of roles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleResponse'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setUserRoles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetRolesRequest'];
      };
    };
    responses: {
      /** @description Roles updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:assign permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  assignRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
        /** @description Role ID */
        roleId: components['parameters']['RoleId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Role assigned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:assign permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User or role not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role already assigned */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  revokeRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
        /** @description Role ID */
        roleId: components['parameters']['RoleId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Role revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:assign permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User or role not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getUserPermissions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of permissions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': string[];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listRoles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of roles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleResponse'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:list permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createRole: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRoleRequest'];
      };
    };
    responses: {
      /** @description Role created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:create permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role name already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Role ID */
        id: components['parameters']['RoleIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Role details with permissions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleWithPermissionsResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:read permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Role ID */
        id: components['parameters']['RoleIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRoleRequest'];
      };
    };
    responses: {
      /** @description Role updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleResponse'];
        };
      };
      /** @description Invalid input or system role modification */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:update permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Role ID */
        id: components['parameters']['RoleIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Role deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot delete system or default role */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:delete permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role is assigned to users */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setRolePermissions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Role ID */
        id: components['parameters']['RoleIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetPermissionsRequest'];
      };
    };
    responses: {
      /** @description Permissions updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:update permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  addPermissionToRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Role ID */
        id: components['parameters']['RoleIdPath'];
        /** @description Permission ID */
        permissionId: components['parameters']['PermissionId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Permission added */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:update permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role or permission not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission already assigned */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  removePermissionFromRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Role ID */
        id: components['parameters']['RoleIdPath'];
        /** @description Permission ID */
        permissionId: components['parameters']['PermissionId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Permission removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:update permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role or permission not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getUsersWithRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Role ID */
        id: components['parameters']['RoleIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Users with role */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires roles:read permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listPermissions: {
    parameters: {
      query?: {
        /** @description Filter by resource (e.g., "users", "roles") */
        resource?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of permissions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PermissionResponse'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires permissions:list permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createPermission: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePermissionRequest'];
      };
    };
    responses: {
      /** @description Permission created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PermissionResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires permissions:create permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission code already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getPermission: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Permission ID */
        id: components['parameters']['PermissionIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Permission details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PermissionResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires permissions:read permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updatePermission: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Permission ID */
        id: components['parameters']['PermissionIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePermissionRequest'];
      };
    };
    responses: {
      /** @description Permission updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PermissionResponse'];
        };
      };
      /** @description Invalid input or system permission */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires permissions:update permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deletePermission: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Permission ID */
        id: components['parameters']['PermissionIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Permission deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot delete system permission */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - requires permissions:delete permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission is assigned to roles */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
