#!/usr/bin/env bash
# =============================================================================
# TypeScript Type Generation Script
# =============================================================================
# Generates TypeScript types from Go backend for frontend consumption.
# Supports multiple generation methods:
#   - OpenAPI spec generation (oapi-codegen)
#   - Go struct to TypeScript (tygo)
#   - Manual type extraction
# =============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Project paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BACKEND_DIR="$PROJECT_ROOT/backend"
FRONTEND_DIR="$PROJECT_ROOT/frontend"
TYPES_OUTPUT_DIR="$FRONTEND_DIR/src/types"
OPENAPI_SPEC="$BACKEND_DIR/api/openapi.yaml"

# =============================================================================
# Helper Functions
# =============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

ensure_dir() {
    mkdir -p "$1"
}

# =============================================================================
# Type Generation Methods
# =============================================================================

# Generate types from OpenAPI specification
generate_from_openapi() {
    log_info "Generating types from OpenAPI specification..."

    if [ ! -f "$OPENAPI_SPEC" ]; then
        log_warn "OpenAPI spec not found at $OPENAPI_SPEC"
        return 1
    fi

    ensure_dir "$TYPES_OUTPUT_DIR/generated"

    # Use openapi-typescript if available
    if command -v npx &> /dev/null; then
        log_info "Using openapi-typescript..."
        npx openapi-typescript "$OPENAPI_SPEC" -o "$TYPES_OUTPUT_DIR/generated/api.ts"
        log_success "Generated types at $TYPES_OUTPUT_DIR/generated/api.ts"
        return 0
    fi

    log_warn "npx not available, skipping OpenAPI generation"
    return 1
}

# Generate types using tygo (Go struct to TypeScript)
generate_with_tygo() {
    log_info "Generating types with tygo..."

    if ! command -v tygo &> /dev/null; then
        log_info "Installing tygo..."
        go install github.com/gzuidhof/tygo@latest
    fi

    # Check for tygo config
    if [ -f "$BACKEND_DIR/tygo.yaml" ]; then
        cd "$BACKEND_DIR"
        tygo generate
        log_success "Generated types with tygo"
        return 0
    fi

    # Create default tygo config if not exists
    log_info "Creating tygo configuration..."
    cat > "$BACKEND_DIR/tygo.yaml" << 'EOF'
packages:
  - path: "github.com/yourorg/backend/internal/application/dto"
    output_path: "../frontend/src/types/generated/dto.ts"
    type_mappings:
      time.Time: "string"
      uuid.UUID: "string"
      decimal.Decimal: "string"

  - path: "github.com/yourorg/backend/internal/domain/user"
    output_path: "../frontend/src/types/generated/user.ts"
    type_mappings:
      time.Time: "string"
      uuid.UUID: "string"
EOF

    log_warn "Created tygo.yaml - please update package paths and run again"
    return 1
}

# Generate types from Go DTOs manually
generate_from_dto() {
    log_info "Extracting types from Go DTOs..."

    local dto_dir="$BACKEND_DIR/internal/application/dto"
    local output_file="$TYPES_OUTPUT_DIR/generated/api-types.ts"

    if [ ! -d "$dto_dir" ]; then
        log_warn "DTO directory not found at $dto_dir"
        return 1
    fi

    ensure_dir "$TYPES_OUTPUT_DIR/generated"

    # Generate header
    cat > "$output_file" << 'EOF'
// =============================================================================
// Auto-generated TypeScript types from Go backend
// Generated at: $(date -Iseconds)
// DO NOT EDIT - This file is automatically generated
// =============================================================================

EOF

    # Extract struct definitions and convert to TypeScript
    # This is a basic implementation - consider using tygo for complex projects

    log_info "Parsing Go files in $dto_dir..."

    for file in "$dto_dir"/*.go; do
        if [ -f "$file" ]; then
            log_info "Processing $(basename "$file")..."

            # Extract struct definitions (basic parsing)
            awk '
            /^type [A-Z][a-zA-Z]+ struct/ {
                # Get struct name
                gsub(/type /, "")
                gsub(/ struct.*/, "")
                struct_name = $0
                print "export interface " struct_name " {"
                in_struct = 1
                next
            }
            in_struct && /^}/ {
                print "}"
                print ""
                in_struct = 0
                next
            }
            in_struct && /[A-Z][a-zA-Z]+/ {
                # Parse field
                line = $0
                gsub(/^\t+/, "", line)
                gsub(/^ +/, "", line)

                # Skip empty lines and comments
                if (line == "" || line ~ /^\/\//) next

                # Extract field name and type
                split(line, parts, " ")
                field_name = parts[1]
                field_type = parts[2]

                # Convert Go types to TypeScript
                ts_type = field_type
                if (field_type == "string") ts_type = "string"
                else if (field_type == "int" || field_type == "int64" || field_type == "int32" || field_type == "float64" || field_type == "float32") ts_type = "number"
                else if (field_type == "bool") ts_type = "boolean"
                else if (field_type ~ /\[\]/) {
                    gsub(/\[\]/, "", field_type)
                    ts_type = field_type "[]"
                }
                else if (field_type == "time.Time") ts_type = "string"
                else if (field_type == "uuid.UUID") ts_type = "string"

                # Convert to camelCase
                camel_name = tolower(substr(field_name, 1, 1)) substr(field_name, 2)

                # Check for json tag
                if (line ~ /json:"[^"]+"/) {
                    match(line, /json:"([^"]+)"/, tag)
                    if (tag[1] != "" && tag[1] != "-") {
                        split(tag[1], json_parts, ",")
                        camel_name = json_parts[1]
                    }
                }

                # Check if optional (omitempty)
                optional = ""
                if (line ~ /omitempty/) optional = "?"

                print "  " camel_name optional ": " ts_type ";"
            }
            ' "$file" >> "$output_file"
        fi
    done

    log_success "Generated types at $output_file"
}

# Copy pre-generated types from backend
copy_generated_types() {
    log_info "Copying pre-generated types from backend..."

    local backend_types="$BACKEND_DIR/src/types/api.d.ts"
    local backend_types_alt="$BACKEND_DIR/types/api.d.ts"

    ensure_dir "$TYPES_OUTPUT_DIR"

    if [ -f "$backend_types" ]; then
        cp "$backend_types" "$TYPES_OUTPUT_DIR/api.d.ts"
        log_success "Copied types to $TYPES_OUTPUT_DIR/api.d.ts"
        return 0
    elif [ -f "$backend_types_alt" ]; then
        cp "$backend_types_alt" "$TYPES_OUTPUT_DIR/api.d.ts"
        log_success "Copied types to $TYPES_OUTPUT_DIR/api.d.ts"
        return 0
    fi

    log_warn "No pre-generated types found in backend"
    return 1
}

# Create base type definitions
create_base_types() {
    log_info "Creating base type definitions..."

    ensure_dir "$TYPES_OUTPUT_DIR"

    local base_file="$TYPES_OUTPUT_DIR/index.ts"

    if [ ! -f "$base_file" ]; then
        cat > "$base_file" << 'EOF'
// =============================================================================
// Type Definitions Index
// =============================================================================

// Re-export generated types
export * from './generated/api-types';

// =============================================================================
// Common Types
// =============================================================================

export interface ApiResponse<T> {
  data: T;
  meta?: {
    page?: number;
    limit?: number;
    total?: number;
  };
}

export interface ApiError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

export interface PaginationParams {
  page?: number;
  limit?: number;
  sort?: string;
  order?: 'asc' | 'desc';
}

// =============================================================================
// Entity Base Types
// =============================================================================

export interface BaseEntity {
  id: string;
  createdAt: string;
  updatedAt: string;
}

export interface User extends BaseEntity {
  email: string;
  name: string;
  role: 'admin' | 'user' | 'guest';
  avatar?: string;
}

export interface CreateUserInput {
  email: string;
  name: string;
  password: string;
}

export interface UpdateUserInput {
  name?: string;
  avatar?: string;
}
EOF
        log_success "Created base types at $base_file"
    else
        log_info "Base types already exist at $base_file"
    fi
}

# =============================================================================
# Main
# =============================================================================

main() {
    log_info "Starting TypeScript type generation..."
    echo ""

    cd "$PROJECT_ROOT"

    # Ensure output directory exists
    ensure_dir "$TYPES_OUTPUT_DIR/generated"

    # Try different generation methods in order of preference
    local generated=false

    # Method 1: OpenAPI spec
    if generate_from_openapi 2>/dev/null; then
        generated=true
    fi

    # Method 2: tygo
    if [ "$generated" = false ]; then
        if generate_with_tygo 2>/dev/null; then
            generated=true
        fi
    fi

    # Method 3: Manual DTO extraction
    if [ "$generated" = false ]; then
        if generate_from_dto 2>/dev/null; then
            generated=true
        fi
    fi

    # Method 4: Copy pre-generated types
    if [ "$generated" = false ]; then
        if copy_generated_types 2>/dev/null; then
            generated=true
        fi
    fi

    # Always create/update base types
    create_base_types

    echo ""
    if [ "$generated" = true ]; then
        log_success "Type generation completed!"
    else
        log_warn "No types were generated from backend"
        log_info "Base types have been created at $TYPES_OUTPUT_DIR"
    fi

    echo ""
    log_info "Generated files:"
    find "$TYPES_OUTPUT_DIR" -name "*.ts" -type f 2>/dev/null | while read -r file; do
        echo "  - ${file#$PROJECT_ROOT/}"
    done
}

main "$@"
